# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.25.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [34]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.85114607 0.48748877 0.37410095 0.49230242 0.11629178]
  [0.26735448 0.05737239 0.68990778 0.02513563 0.19975106]
  [0.55838288 0.90379765 0.02516583 0.27786919 0.53992426]]

 [[0.51086756 0.25073376 0.6692394  0.12758107 0.75358495]
  [0.58652544 0.09934239 0.5505413  0.87124015 0.14308645]
  [0.97544337 0.0903775  0.09730927 0.2608678  0.86930676]]]


In [11]:
# Method 2
a = np.random.randint(1, 101, size=(2, 3, 5))
print(a)

[[[25 80  2 31 80]
  [42 13 11 37 20]
  [79  5 64 24 67]]

 [[67 65 67 90 79]
  [80 21 42 23  5]
  [77 64 76 27  1]]]


In [12]:
# Method 3


#### 4. Print *a*.


In [24]:
# your code here
print(a)

[[[25 80  2 31 80]
  [42 13 11 37 20]
  [79  5 64 24 67]]

 [[67 65 67 90 79]
  [80 21 42 23  5]
  [77 64 76 27  1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [31]:
# your code here
b = np.ones((5,3,2))

#### 6. Print *b*.


In [32]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [33]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [34]:
# your answer here
c = a + b
print(c)
#We can´t do it due to "a" & "b" haven´t the same size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [35]:
# your code here
c = b.transpose()
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [38]:
# your code/answer here
d = a + c
d
#We can sum (a+c) because a is an array 2x3x5 and d is an array 2x3x5

array([[[26., 81.,  3., 32., 81.],
        [43., 14., 12., 38., 21.],
        [80.,  6., 65., 25., 68.]],

       [[68., 66., 68., 91., 80.],
        [81., 22., 43., 24.,  6.],
        [78., 65., 77., 28.,  2.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
# your code/answer here
print(a)

print(d)
#Each value of d is a + 1

[[[25 80  2 31 80]
  [42 13 11 37 20]
  [79  5 64 24 67]]

 [[67 65 67 90 79]
  [80 21 42 23  5]
  [77 64 76 27  1]]]
[[[26. 81.  3. 32. 81.]
  [43. 14. 12. 38. 21.]
  [80.  6. 65. 25. 68.]]

 [[68. 66. 68. 91. 80.]
  [81. 22. 43. 24.  6.]
  [78. 65. 77. 28.  2.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [42]:
# your code here
e = a * c
e

array([[[25., 80.,  2., 31., 80.],
        [42., 13., 11., 37., 20.],
        [79.,  5., 64., 24., 67.]],

       [[67., 65., 67., 90., 79.],
        [80., 21., 42., 23.,  5.],
        [77., 64., 76., 27.,  1.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [45]:
# your code/answer here
e.shape == a.shape
#e.shape and a.shape are 2x3x5

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [52]:
# your code here
d_max = d.max()
print(f"{d_max} is the max")
d_min = d.min()
print(f"{d_min} is the min")
d_mean = d.mean()
print(f"{d_mean} is the mean")

91.0 is the max
2.0 is the min
46.46666666666667 is the mean


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[25. 80.  2. 31. 80.]
  [42. 13. 11. 37. 20.]
  [79.  5. 64. 24. 67.]]

 [[67. 65. 67. 90. 79.]
  [80. 21. 42. 23.  5.]
  [77. 64. 76. 27.  1.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here